--- # pod creation
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: efs-static-demo
    project: roboshop
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-static
--- # service ncreation Loadbalancer
apiVersion: v1
kind: Service
metadata: 
  name: ebs-static
  labels:
    purpose: efs-static-demo
    project: roboshop
spec:
  type: LoadBalancer
  selector: 
    purpose: efs-static-demo
    project: roboshop
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port